// <auto-generated />
namespace Practical_13.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Iitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Iitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202306281341120_Iitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
